### ISSUE TITLE
.Net Core Bundles

### ISSUE THREAD

**Issue by TheHellTower** [prowlynx/ProwlynxNET#1]
Hello, It doesn't looks like it but does it or will you add support for .Net Core Bundles in this Engine ?

**Comment by Elliesaur** [comment]
If it isn't loadable by AsmResolver then it will not be loadable by this. I am unsure as to what exactly you are referring to by "bundles".

**Comment by TheHellTower** [comment]
> If it isn't loadable by AsmResolver then it will not be loadable by this. I am unsure as to what exactly you are referring to by "bundles".
I mean [single-file executable](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli) / https://www.youtube.com/watch?v=QJg1ptS0At0

**Comment by Elliesaur** [comment]
Thank you for more information on the subject, unless AsmResolver supports this there is no support from this project. 

I don't see why you couldn't protect the .NET files before they are bundled though.

**Comment by TheHellTower** [comment]
> Thank you for more information on the subject, unless AsmResolver supports this there is no support from this project.
> 
> I don't see why you couldn't protect the .NET files before they are bundled though.

I'm pretty sure without a VS extension you can't protect before bundling..
Also wanted to know because apparently engines from protector like [DNR](https://www.eziriz.com/dotnet_reactor.htm) support it and I would've had liked to know how exactly ! I'm curious :)
